#ifndef IMAGE_CM_READER_HPP
#define IMAGE_CM_READER_HPP

#include "Platform.hpp"
#include "ImageReader.hpp"
#include "HuffmanDecoder.hpp"

/*
 * Game Closure Context Modeling (GC-CM) Decompression
 *
 * The decompressor rebuilds the static Huffman tables generated by the encoder
 * and then iterates over each pixel from upper left to lower right.  Where the
 * Fully-Transparent Alpha mask is set, it emits a transparent black pixel.
 * Where the 2D LZ Exact Match algorithm triggers, it performs LZ decoding.
 *
 * For the remaining pixels, the BCIF "chaos" metric selects which Huffman
 * tables to use, and filtered pixel values are emitted.  The YUV color data is
 * then reversed to RGB and then the spatial filter is reversed back to the
 * original RGB data.
 *
 * LZ and alpha masking are very cheap decoding operations.  The most expensive
 * per-pixel operation is the static Huffman decoding, which is just a table
 * lookup and some bit twiddling for the majority of decoding.  As a result the
 * decoder is exceptionally fast.  It reaches for the Pareto Frontier.
 */

namespace cat {


//#define FUZZY_CHAOS


//// ImageCMReader

class ImageCMReader {
public:
#ifdef FUZZY_CHAOS
	static const int CHAOS_LEVELS = 16;
#else
	static const int CHAOS_LEVELS = 8;
#endif

protected:
	HuffmanDecoder _decoder[3][CHAOS_LEVELS];

	void clear();

	int init(const ImageInfo *info);
	int readFilters(ImageReader &reader);
	int readTables(ImageReader &reader);
	int readRGB(ImageReader &reader);

#ifdef CAT_COLLECT_STATS
public:
	struct _Stats {
	} Stats;
#endif

public:
	CAT_INLINE ImageCMReader() {
	}
	virtual CAT_INLINE ~ImageCMReader() {
		clear();
	}

	int read(ImageReader &reader);

#ifdef CAT_COLLECT_STATS
	bool dumpStats();
#else
	CAT_INLINE bool dumpStats() {
		return false;
	}
#endif
};


} // namespace cat

#endif // IMAGE_CM_READER_HPP

